
import './globals.css'
import { useState } from 'react'
import Link from 'next/link'
import {css } from '@emotion/css'
import {ethers} from 'ethers'
import Web3Modal from 'web3modal'
import WalletConnectProvider from '@walletconnect/web3-provider'
import { AccountContext } from '@/context'
import { ownerAddress } from '@/config'
import 'easymde/dist/easymde.min.css'

function App( {Component, pageProps }) {
  const [account, setAccount ] = useState(null) 


  async function getWeb3Modal() {
    const web3Modal = new Web3Modal({
      cacheProvider: false,
      providerOptions: {
        walletconnect: {
          package: WalletConnectProvider,
          options: {
            infuraId: "id"
      },
     }, 
    },
}) 
return web3Modal
}
}

// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
